/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_syberos_jnidemo_TestJNI */

#ifndef _Included_cn_syberos_jnidemo_TestJNI
#define _Included_cn_syberos_jnidemo_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_syberos_jnidemo_TestJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_syberos_jnidemo_TestJNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
